/*
 * generated by Xtext 2.38.0
 */
package org.expleo.sarch.dsl.ide;


/**
 * Use this class to register ide components.
 */
public class SoftwareArchitectureDslIdeModule extends AbstractSoftwareArchitectureDslIdeModule {
}
