/*
 * generated by Xtext 2.38.0
 */
package org.expleo.sarch.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.expleo.sarch.dsl.SoftwareArchitectureDslRuntimeModule;
import org.expleo.sarch.dsl.SoftwareArchitectureDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SoftwareArchitectureDslIdeSetup extends SoftwareArchitectureDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SoftwareArchitectureDslRuntimeModule(), new SoftwareArchitectureDslIdeModule()));
	}
	
}
