/*
 * generated by Xtext 2.38.0
 */
package org.expleo.sarch.dsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.expleo.sarch.dsl.parser.antlr.internal.InternalSoftwareArchitectureDslParser;
import org.expleo.sarch.dsl.services.SoftwareArchitectureDslGrammarAccess;

public class SoftwareArchitectureDslParser extends AbstractAntlrParser {

	@Inject
	private SoftwareArchitectureDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSoftwareArchitectureDslParser createParser(XtextTokenStream stream) {
		return new InternalSoftwareArchitectureDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Architecture";
	}

	public SoftwareArchitectureDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SoftwareArchitectureDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
