/*
 * generated by Xtext 2.38.0
 */
package org.expleo.sarch.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SoftwareArchitectureDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/expleo/sarch/dsl/parser/antlr/internal/InternalSoftwareArchitectureDsl.tokens");
	}
}
