/**
 * generated by Xtext 2.38.0
 */
package org.expleo.sarch.dsl.softwareArchitectureDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.expleo.sarch.dsl.softwareArchitectureDsl.PPort;
import org.expleo.sarch.dsl.softwareArchitectureDsl.SoftwareArchitectureDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>PPort</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PPortImpl extends PortImpl implements PPort
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PPortImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SoftwareArchitectureDslPackage.Literals.PPORT;
  }

} //PPortImpl
