/*
 * generated by Xtext 2.38.0
 */
package org.expleo.sarch.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SoftwareArchitectureDslStandaloneSetup extends SoftwareArchitectureDslStandaloneSetupGenerated {

	public static void doSetup() {
		new SoftwareArchitectureDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
