/**
 * generated by Xtext 2.38.0
 */
package org.expleo.sarch.dsl.softwareArchitectureDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.expleo.sarch.dsl.softwareArchitectureDsl.RPort;
import org.expleo.sarch.dsl.softwareArchitectureDsl.SoftwareArchitectureDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>RPort</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RPortImpl extends PortImpl implements RPort
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RPortImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SoftwareArchitectureDslPackage.Literals.RPORT;
  }

} //RPortImpl
