/*
 * generated by Xtext 2.38.0
 */
package org.expleo.sarch.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SoftwareArchitectureDslUiModule extends AbstractSoftwareArchitectureDslUiModule {

	public SoftwareArchitectureDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
}
