/*
 * generated by Xtext 2.38.0
 */
package org.expleo.sarch.dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractSoftwareArchitectureDslValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.expleo.sarch.dsl.softwareArchitectureDsl.SoftwareArchitectureDslPackage.eINSTANCE);
		return result;
	}
}
