/**
 * generated by Xtext 2.38.0
 */
package org.expleo.sarch.dsl.softwareArchitectureDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>RPort</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.expleo.sarch.dsl.softwareArchitectureDsl.SoftwareArchitectureDslPackage#getRPort()
 * @model
 * @generated
 */
public interface RPort extends Port
{
} // RPort
