/**
 * generated by Xtext 2.38.0
 */
package org.expleo.sarch.dsl.softwareArchitectureDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.expleo.sarch.dsl.softwareArchitectureDsl.SoftwareArchitectureDslFactory
 * @model kind="package"
 * @generated
 */
public interface SoftwareArchitectureDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "softwareArchitectureDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.expleo.org/sarch/dsl/SoftwareArchitectureDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "softwareArchitectureDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SoftwareArchitectureDslPackage eINSTANCE = org.expleo.sarch.dsl.softwareArchitectureDsl.impl.SoftwareArchitectureDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.expleo.sarch.dsl.softwareArchitectureDsl.impl.ArchitectureImpl <em>Architecture</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.expleo.sarch.dsl.softwareArchitectureDsl.impl.ArchitectureImpl
   * @see org.expleo.sarch.dsl.softwareArchitectureDsl.impl.SoftwareArchitectureDslPackageImpl#getArchitecture()
   * @generated
   */
  int ARCHITECTURE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARCHITECTURE__NAME = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARCHITECTURE__ELEMENTS = 1;

  /**
   * The number of structural features of the '<em>Architecture</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARCHITECTURE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.expleo.sarch.dsl.softwareArchitectureDsl.impl.ArchitectureElementImpl <em>Architecture Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.expleo.sarch.dsl.softwareArchitectureDsl.impl.ArchitectureElementImpl
   * @see org.expleo.sarch.dsl.softwareArchitectureDsl.impl.SoftwareArchitectureDslPackageImpl#getArchitectureElement()
   * @generated
   */
  int ARCHITECTURE_ELEMENT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARCHITECTURE_ELEMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Architecture Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARCHITECTURE_ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.expleo.sarch.dsl.softwareArchitectureDsl.impl.InterfaceImpl <em>Interface</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.expleo.sarch.dsl.softwareArchitectureDsl.impl.InterfaceImpl
   * @see org.expleo.sarch.dsl.softwareArchitectureDsl.impl.SoftwareArchitectureDslPackageImpl#getInterface()
   * @generated
   */
  int INTERFACE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERFACE__NAME = ARCHITECTURE_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERFACE__ELEMENTS = ARCHITECTURE_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Interface</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERFACE_FEATURE_COUNT = ARCHITECTURE_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.expleo.sarch.dsl.softwareArchitectureDsl.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.expleo.sarch.dsl.softwareArchitectureDsl.impl.ElementImpl
   * @see org.expleo.sarch.dsl.softwareArchitectureDsl.impl.SoftwareArchitectureDslPackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 3;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__TYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__NAME = 1;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.expleo.sarch.dsl.softwareArchitectureDsl.impl.ComponentImpl <em>Component</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.expleo.sarch.dsl.softwareArchitectureDsl.impl.ComponentImpl
   * @see org.expleo.sarch.dsl.softwareArchitectureDsl.impl.SoftwareArchitectureDslPackageImpl#getComponent()
   * @generated
   */
  int COMPONENT = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__NAME = ARCHITECTURE_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Ports</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__PORTS = ARCHITECTURE_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Component</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_FEATURE_COUNT = ARCHITECTURE_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.expleo.sarch.dsl.softwareArchitectureDsl.impl.PortImpl <em>Port</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.expleo.sarch.dsl.softwareArchitectureDsl.impl.PortImpl
   * @see org.expleo.sarch.dsl.softwareArchitectureDsl.impl.SoftwareArchitectureDslPackageImpl#getPort()
   * @generated
   */
  int PORT = 5;

  /**
   * The feature id for the '<em><b>Interface</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORT__INTERFACE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORT__NAME = 1;

  /**
   * The number of structural features of the '<em>Port</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.expleo.sarch.dsl.softwareArchitectureDsl.impl.PPortImpl <em>PPort</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.expleo.sarch.dsl.softwareArchitectureDsl.impl.PPortImpl
   * @see org.expleo.sarch.dsl.softwareArchitectureDsl.impl.SoftwareArchitectureDslPackageImpl#getPPort()
   * @generated
   */
  int PPORT = 6;

  /**
   * The feature id for the '<em><b>Interface</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PPORT__INTERFACE = PORT__INTERFACE;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PPORT__NAME = PORT__NAME;

  /**
   * The number of structural features of the '<em>PPort</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PPORT_FEATURE_COUNT = PORT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.expleo.sarch.dsl.softwareArchitectureDsl.impl.RPortImpl <em>RPort</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.expleo.sarch.dsl.softwareArchitectureDsl.impl.RPortImpl
   * @see org.expleo.sarch.dsl.softwareArchitectureDsl.impl.SoftwareArchitectureDslPackageImpl#getRPort()
   * @generated
   */
  int RPORT = 7;

  /**
   * The feature id for the '<em><b>Interface</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RPORT__INTERFACE = PORT__INTERFACE;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RPORT__NAME = PORT__NAME;

  /**
   * The number of structural features of the '<em>RPort</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RPORT_FEATURE_COUNT = PORT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.expleo.sarch.dsl.softwareArchitectureDsl.DataType <em>Data Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.expleo.sarch.dsl.softwareArchitectureDsl.DataType
   * @see org.expleo.sarch.dsl.softwareArchitectureDsl.impl.SoftwareArchitectureDslPackageImpl#getDataType()
   * @generated
   */
  int DATA_TYPE = 8;


  /**
   * Returns the meta object for class '{@link org.expleo.sarch.dsl.softwareArchitectureDsl.Architecture <em>Architecture</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Architecture</em>'.
   * @see org.expleo.sarch.dsl.softwareArchitectureDsl.Architecture
   * @generated
   */
  EClass getArchitecture();

  /**
   * Returns the meta object for the attribute '{@link org.expleo.sarch.dsl.softwareArchitectureDsl.Architecture#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.expleo.sarch.dsl.softwareArchitectureDsl.Architecture#getName()
   * @see #getArchitecture()
   * @generated
   */
  EAttribute getArchitecture_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.expleo.sarch.dsl.softwareArchitectureDsl.Architecture#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.expleo.sarch.dsl.softwareArchitectureDsl.Architecture#getElements()
   * @see #getArchitecture()
   * @generated
   */
  EReference getArchitecture_Elements();

  /**
   * Returns the meta object for class '{@link org.expleo.sarch.dsl.softwareArchitectureDsl.ArchitectureElement <em>Architecture Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Architecture Element</em>'.
   * @see org.expleo.sarch.dsl.softwareArchitectureDsl.ArchitectureElement
   * @generated
   */
  EClass getArchitectureElement();

  /**
   * Returns the meta object for the attribute '{@link org.expleo.sarch.dsl.softwareArchitectureDsl.ArchitectureElement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.expleo.sarch.dsl.softwareArchitectureDsl.ArchitectureElement#getName()
   * @see #getArchitectureElement()
   * @generated
   */
  EAttribute getArchitectureElement_Name();

  /**
   * Returns the meta object for class '{@link org.expleo.sarch.dsl.softwareArchitectureDsl.Interface <em>Interface</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Interface</em>'.
   * @see org.expleo.sarch.dsl.softwareArchitectureDsl.Interface
   * @generated
   */
  EClass getInterface();

  /**
   * Returns the meta object for the containment reference list '{@link org.expleo.sarch.dsl.softwareArchitectureDsl.Interface#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.expleo.sarch.dsl.softwareArchitectureDsl.Interface#getElements()
   * @see #getInterface()
   * @generated
   */
  EReference getInterface_Elements();

  /**
   * Returns the meta object for class '{@link org.expleo.sarch.dsl.softwareArchitectureDsl.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see org.expleo.sarch.dsl.softwareArchitectureDsl.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for the attribute '{@link org.expleo.sarch.dsl.softwareArchitectureDsl.Element#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.expleo.sarch.dsl.softwareArchitectureDsl.Element#getType()
   * @see #getElement()
   * @generated
   */
  EAttribute getElement_Type();

  /**
   * Returns the meta object for the attribute '{@link org.expleo.sarch.dsl.softwareArchitectureDsl.Element#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.expleo.sarch.dsl.softwareArchitectureDsl.Element#getName()
   * @see #getElement()
   * @generated
   */
  EAttribute getElement_Name();

  /**
   * Returns the meta object for class '{@link org.expleo.sarch.dsl.softwareArchitectureDsl.Component <em>Component</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Component</em>'.
   * @see org.expleo.sarch.dsl.softwareArchitectureDsl.Component
   * @generated
   */
  EClass getComponent();

  /**
   * Returns the meta object for the containment reference list '{@link org.expleo.sarch.dsl.softwareArchitectureDsl.Component#getPorts <em>Ports</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Ports</em>'.
   * @see org.expleo.sarch.dsl.softwareArchitectureDsl.Component#getPorts()
   * @see #getComponent()
   * @generated
   */
  EReference getComponent_Ports();

  /**
   * Returns the meta object for class '{@link org.expleo.sarch.dsl.softwareArchitectureDsl.Port <em>Port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Port</em>'.
   * @see org.expleo.sarch.dsl.softwareArchitectureDsl.Port
   * @generated
   */
  EClass getPort();

  /**
   * Returns the meta object for the reference '{@link org.expleo.sarch.dsl.softwareArchitectureDsl.Port#getInterface <em>Interface</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Interface</em>'.
   * @see org.expleo.sarch.dsl.softwareArchitectureDsl.Port#getInterface()
   * @see #getPort()
   * @generated
   */
  EReference getPort_Interface();

  /**
   * Returns the meta object for the attribute '{@link org.expleo.sarch.dsl.softwareArchitectureDsl.Port#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.expleo.sarch.dsl.softwareArchitectureDsl.Port#getName()
   * @see #getPort()
   * @generated
   */
  EAttribute getPort_Name();

  /**
   * Returns the meta object for class '{@link org.expleo.sarch.dsl.softwareArchitectureDsl.PPort <em>PPort</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>PPort</em>'.
   * @see org.expleo.sarch.dsl.softwareArchitectureDsl.PPort
   * @generated
   */
  EClass getPPort();

  /**
   * Returns the meta object for class '{@link org.expleo.sarch.dsl.softwareArchitectureDsl.RPort <em>RPort</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>RPort</em>'.
   * @see org.expleo.sarch.dsl.softwareArchitectureDsl.RPort
   * @generated
   */
  EClass getRPort();

  /**
   * Returns the meta object for enum '{@link org.expleo.sarch.dsl.softwareArchitectureDsl.DataType <em>Data Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Data Type</em>'.
   * @see org.expleo.sarch.dsl.softwareArchitectureDsl.DataType
   * @generated
   */
  EEnum getDataType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SoftwareArchitectureDslFactory getSoftwareArchitectureDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.expleo.sarch.dsl.softwareArchitectureDsl.impl.ArchitectureImpl <em>Architecture</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.expleo.sarch.dsl.softwareArchitectureDsl.impl.ArchitectureImpl
     * @see org.expleo.sarch.dsl.softwareArchitectureDsl.impl.SoftwareArchitectureDslPackageImpl#getArchitecture()
     * @generated
     */
    EClass ARCHITECTURE = eINSTANCE.getArchitecture();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARCHITECTURE__NAME = eINSTANCE.getArchitecture_Name();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARCHITECTURE__ELEMENTS = eINSTANCE.getArchitecture_Elements();

    /**
     * The meta object literal for the '{@link org.expleo.sarch.dsl.softwareArchitectureDsl.impl.ArchitectureElementImpl <em>Architecture Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.expleo.sarch.dsl.softwareArchitectureDsl.impl.ArchitectureElementImpl
     * @see org.expleo.sarch.dsl.softwareArchitectureDsl.impl.SoftwareArchitectureDslPackageImpl#getArchitectureElement()
     * @generated
     */
    EClass ARCHITECTURE_ELEMENT = eINSTANCE.getArchitectureElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARCHITECTURE_ELEMENT__NAME = eINSTANCE.getArchitectureElement_Name();

    /**
     * The meta object literal for the '{@link org.expleo.sarch.dsl.softwareArchitectureDsl.impl.InterfaceImpl <em>Interface</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.expleo.sarch.dsl.softwareArchitectureDsl.impl.InterfaceImpl
     * @see org.expleo.sarch.dsl.softwareArchitectureDsl.impl.SoftwareArchitectureDslPackageImpl#getInterface()
     * @generated
     */
    EClass INTERFACE = eINSTANCE.getInterface();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTERFACE__ELEMENTS = eINSTANCE.getInterface_Elements();

    /**
     * The meta object literal for the '{@link org.expleo.sarch.dsl.softwareArchitectureDsl.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.expleo.sarch.dsl.softwareArchitectureDsl.impl.ElementImpl
     * @see org.expleo.sarch.dsl.softwareArchitectureDsl.impl.SoftwareArchitectureDslPackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT__TYPE = eINSTANCE.getElement_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT__NAME = eINSTANCE.getElement_Name();

    /**
     * The meta object literal for the '{@link org.expleo.sarch.dsl.softwareArchitectureDsl.impl.ComponentImpl <em>Component</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.expleo.sarch.dsl.softwareArchitectureDsl.impl.ComponentImpl
     * @see org.expleo.sarch.dsl.softwareArchitectureDsl.impl.SoftwareArchitectureDslPackageImpl#getComponent()
     * @generated
     */
    EClass COMPONENT = eINSTANCE.getComponent();

    /**
     * The meta object literal for the '<em><b>Ports</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT__PORTS = eINSTANCE.getComponent_Ports();

    /**
     * The meta object literal for the '{@link org.expleo.sarch.dsl.softwareArchitectureDsl.impl.PortImpl <em>Port</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.expleo.sarch.dsl.softwareArchitectureDsl.impl.PortImpl
     * @see org.expleo.sarch.dsl.softwareArchitectureDsl.impl.SoftwareArchitectureDslPackageImpl#getPort()
     * @generated
     */
    EClass PORT = eINSTANCE.getPort();

    /**
     * The meta object literal for the '<em><b>Interface</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PORT__INTERFACE = eINSTANCE.getPort_Interface();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PORT__NAME = eINSTANCE.getPort_Name();

    /**
     * The meta object literal for the '{@link org.expleo.sarch.dsl.softwareArchitectureDsl.impl.PPortImpl <em>PPort</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.expleo.sarch.dsl.softwareArchitectureDsl.impl.PPortImpl
     * @see org.expleo.sarch.dsl.softwareArchitectureDsl.impl.SoftwareArchitectureDslPackageImpl#getPPort()
     * @generated
     */
    EClass PPORT = eINSTANCE.getPPort();

    /**
     * The meta object literal for the '{@link org.expleo.sarch.dsl.softwareArchitectureDsl.impl.RPortImpl <em>RPort</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.expleo.sarch.dsl.softwareArchitectureDsl.impl.RPortImpl
     * @see org.expleo.sarch.dsl.softwareArchitectureDsl.impl.SoftwareArchitectureDslPackageImpl#getRPort()
     * @generated
     */
    EClass RPORT = eINSTANCE.getRPort();

    /**
     * The meta object literal for the '{@link org.expleo.sarch.dsl.softwareArchitectureDsl.DataType <em>Data Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.expleo.sarch.dsl.softwareArchitectureDsl.DataType
     * @see org.expleo.sarch.dsl.softwareArchitectureDsl.impl.SoftwareArchitectureDslPackageImpl#getDataType()
     * @generated
     */
    EEnum DATA_TYPE = eINSTANCE.getDataType();

  }

} //SoftwareArchitectureDslPackage
