/*
 * generated by Xtext 2.38.0
 */
package org.expleo.sarch.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSoftwareArchitectureDslScopeProvider extends DelegatingScopeProvider {
}
