/*
 * generated by Xtext 2.38.0
 */
package org.expleo.sarch.dsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.expleo.sarch.dsl.ui.internal.DslActivator;

public class SoftwareArchitectureDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("org.expleo.sarch.dsl.SoftwareArchitectureDsl");
	}

}
